name: PR

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk:8

    steps:
    - uses: actions/checkout@v1
    - name: Build
      env:
        GRADLE_OPTS: -Xmx6g -Xms6g -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
      run: ./gradlew build javadoc
